### PR TITLE
Allow manipulation of cell-values and types from the caller.

### PR DESCRIPTION
**Pull request by thomas-brx**
I created this to be able to manipulate the cell values beyond the scope of simple SQL-queries.

### CODE REVIEW

**Comment by bggardner** [comment]
This is a handy utility, but I think it goes beyond the scope of what should be included in the core code.  It seems to me you could do the same thing by looping through the data after it is fetched, which isn't much more burdensome.

**Comment by thomas-brx** [comment]
Fair call.

To be able to do that type of modification I see two options, each requiring a minor change in the core.
```
$cols = $table->getColumnDescriptions();
// Requires new setter in ColumnDescription
$cols[1]->setType(ValueType::TEXT);
foreach ($table->getRows() as $row) {
  $cell = $table->setCell(1, new TableCell(new TextValue('adf')));
}
```

```
// Requires new setter in DataTable
$cols = $table->setColumnDescriptions($idx, new ColumnDescription('cell-id', ValueType::TEXT, 'New Label'));
foreach ($table->getRows() as $row) {
  $cell = $table->setCell(1, new TableCell(new TextValue('adf')));
}
```

Are any/both of those acceptable? If so I'll create a new PR.

**Comment by bggardner** [comment]
Let me preface this with the code is merely a translation of Google's Java code, so I would prefer not to add/change things relating to the core code too much.

Google seems to not want you to alter the columnDescriptions after creating the table, so instead of altering the original table, I would create a new table altogether, which does not require code changes:
```
$newTable = new DataTable();
foreach ($oldTable->getColumnDescriptions() as $i => $col) {
  if ($i == 1) {
    $newTable->addColumn(new ColumnDescription('cell-id', ValueType::TEXT, 'New Label'));
    continue;
  }
  $newTable->addColumn($col);
}
foreach ($oldTable->getRows() as $row) {
  $newRow = clone $row;
  $newRow->setCell(1, new TableCell(new TextValue('adf')));
  $newTable->addRow($newRow);
}
```

**Comment by thomas-brx** [comment]
Thanks, I can live with that. Closing this PR.

**Pull request closed without merging**
